url: https://zendochudo.cl
title: Zendo Chūdō
description: Centro de práctica Zen en Santiago de Chile. Practicamos Zazen presencial y online. Ubicados en La Reina, Metro Plaza Egaña. Práctica dirigida por el monje Zen Oryù Korin.
lang: es
keywords: zen, zazen, meditación, budismo, santiago, chile, la reina, plaza egaña, práctica zen, centro zen
author: Zendo Chūdō
email: zendochudo@gmail.com
social:
  name: Zendo Chūdō
  links:
    - https://web.facebook.com/zendochudo
    - https://www.instagram.com/zendochudo/

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
