url: "https://rcereceda.github.io"
baseurl: "/zendo-chudo"
title: "Zendo Chudo"
lang: "es"

plugins:
  - jekyll-maps
  - jekyll-postcss

postcss:
  cache: false

maps:
  google:
    api_key: <YOUR_KEY>

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
