url: "https://rcereceda.github.io"
baseurl: "/zendo-chudo"
title: "Zendo Chudo"
lang: "es"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
